config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :categories
  
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_menu.rb
class CategoriesMenu < ApplicationRecord
  #relation
  belongs_to :category
	belongs_to :menu
end

app/models/category.rb
class Category < ApplicationRecord
  #relation
  has_many :categories_menus
	has_many :menus, through: :categories_menus

  #validation
  validates :name, presence: true, uniqueness: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  #relation
  has_many :categories_menus
	has_many :categories, through: :categories_menus

  #validation
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 150, too_long: "%{count} characters is the maximum allowed" }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name, :description, :price, :category_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class ="mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category, class: "btn btn-success" %>
  <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>List of Categories</h1>

<%= link_to "New category", new_category_path, class: "btn btn-primary" %>

  <div class="card p-4 my-4">
    <table class="table table-striped table-hover my-2">
  <thead>
    <tr>
      <th scope="col">Categories Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <div id="categories">
        
          <td><%= render category %></td>
          <td>
            <%= link_to "Show",category, class: "btn btn-info" %>
          <td>
        
      </div>
    </tr>
    <% end %>
  </tbody>
</table>
  </div>

app/views/categories/new.html.erb
<h1>New Category Menu</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

  <h2> Detail Categories</h2>
<div class="card mb-3" style="width: 18rem;">
  <div class="card-body">
    <h6> Category name: <br> <%= render @category %></h5>
    <h6> Created at: <br> <%= @category.created_at %></h6>
  </div>
</div>
  <div class="mb-3">
    <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
    <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-success" %>
  </div>
  <%= button_to "Destroy this category", @category, method: :delete %>

app/views/home/index.html.erb
<h1>Welcome to GIGIH Restaurant</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>GIGIH Restaurant</title>
  </head>
  <body>
    <%= render 'partials/header' %>
    <div class="container my-4">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

	<div class="form-group">
    <%= form.label :categories, style: "display: block" %>
    <%= form.collection_select :category_ids, Category.order(:name), :id, :name, {}, { class:"form-control select2", multiple:true, required:true } %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <div class="card my-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= menu.name %></h5>
      <h5 class="card-title text-success"><%= menu.price %></h5>
      <p class="card-text"><%= menu.description %></p>
      <%= link_to "Detail Menu", menu, class:"btn btn-secondary btn-sm" %>
    </div>
  </div>
  

</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menus</h1>
<%= link_to "New menu", new_menu_path, class: "btn btn-primary" %>

<div id="menus">
  <% @menus.each do |menu| %>
    <%= render menu %>
  <% end %>
</div>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<div class="container-fluid py-5 px-5">
	<table>	
		<%= render @menu %>
	</table>
  <div class="card" style="width: 18rem;">
    <div class="card-header">
    Category
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= render @menu.categories%></li>
  </ul>
</div>
</div>
<%= link_to "Back to menus", menus_path %>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
    <div class = "container" 
      <span class="text-muted">@2022 GIGIH Restaurant</span>
    </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'GIGIH Restaurant', root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">GIGIH Restaurant</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Menu', menus_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Order</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">History Order</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Category', categories_path, class: "nav-link" %>
        </li>

      </ul>
    </div>
  </div>
</nav>